author: codeskyblue
description: Port of python supervisor
os: darwin linux windows
includes:
  - README.md
  - LICENSE
  - conf
  - templates
  - public
  - static
  - views
excludes:
  - \.git
script:
  - go get -v
  - sh build.sh
